version: '3.8'

services:
    db:
        image: postgres:16
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123
            POSTGRES_DB: tictactoedb
        ports:
            - "5431:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - tictactoe
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 10

    backend:
        build: ./backend
        ports:
            - "8081:5000"
        depends_on:
            db:
                condition: service_healthy
        networks:
            - tictactoe
    
    frontend:
        build:
            context: ./frontend
        restart: always
        ports:
            - "80:80"
        networks:
            - tictactoe
        depends_on:
            - backend

volumes:
    pgdata:

networks:
    tictactoe:
        driver: bridge
